package parse

import (
	"bytes"
	"io/ioutil"
	"net/http"
	"testing"
)

func TestReadPdfToString(t *testing.T) {
	pdf, err := http.Get("https://science.osti.gov/-/media/wdts/nsb/pdf/HS-Sample-Questions/Sample-Set-13/2019-NSB-HSR-Round-16A.pdf")
	if err != nil {
		t.Logf("failed to get example PDF data with error %q", err)
		t.SkipNow()
	}

	pdfBytes, err := ioutil.ReadAll(pdf.Body)
	if err != nil {
		t.Logf("failed to get byte data from PDF with error %q", err)
		t.SkipNow()
	}

	pdfReader := bytes.NewReader(pdfBytes)
	got, err := ReadPdfToString(pdfReader)

	want := `2019 Regional Science Bowl – Round 16A  Page 1 HIGH SCHOOL - ROUND 16A   TOSS-UP  1) Chemistry  –  Multiple Choice    In a polyelectronic atom, which of the following orbitals would have the lowest energy?   
W) 3s X) 4s Y) 3p Z) 3d   
ANSWER: W) 3s   BONUS  
1) Chemistry  –  Short Answer    Rank the following three carboxylic [CAR-box-IHL-ik] acid derivatives in terms of increasing reactivity to nucleophilic substitution: 1) Amide; 2) Acid 
anhydride; 3) Ester.   
ANSWER: 1, 3, 2  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  2) Math  –  Short Answer    What is f prime of 1 for the function f of x = x times ex ?  ANSWER: 2e   BONUS  2) Math  –  Short Answer    What is the real quadratic polynomial with leading coefficient one that has –5 + 7i as a zero?  ANSWER: x2 + 10x + 74 2019 Regional Science Bowl – Round 16A  Page 2 TOSS-UP  3) Biology  –  Short Answer    What structure in a snail is responsible for secreting its shell?  ANSWER: MANTLE   BONUS  3) Biology  –  Short Answer    In a retrospective study comparing smoking to lung cancer, half of smokers had cancer, while only a quarter of non-smokers had cancer. What is the odds ratio of the association between smoking and cancer?  ANSWER: 3 (ACCEPT: THREE TO ONE)  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  4) Earth and Space  –  Short Answer    What is the name given to asteroids that share an orbit with a larger planet, and lead or trail the planet by 60 degrees?  ANSWER: TROJANS   BONUS  4) Earth and Space  –  Short Answer    The rate of solar rotation was originally determined by observing the movement of what features?   ANSWER: SUNSPOTS 2019 Regional Science Bowl – Round 16A  Page 3 TOSS-UP  5) Physics  –  Short Answer    According to band gap theory, in an insulator at absolute zero, what is the highest band with any electrons in it?   ANSWER: VALENCE   BONUS  5) Physics  –  Short Answer    Nick, who has a mass of 40 kilograms, is inflating his bike tires with a foot-pedal pump that extends 50 centimeters at a 60-degree incline to the ground. If he steps so that his entire weight acts vertically onto the tip of the pedal, then in newton-meters, what is the magnitude of the initial torque [tork] on the pump?  ANSWER: 98  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  6) Energy  –  Multiple Choice    Researchers at SLAC National Accelerator Laboratory have developed a device to produce electromagnetic radiation with a frequency in the terahertz range. Between what two classifications of radiation does terahertz radiation fall?  W) Gamma rays and X-rays X) X-rays and ultraviolet light Y) Ultraviolet light and infrared light Z) Infrared light and microwaves  ANSWER: Z) INFRARED LIGHT AND MICROWAVES   BONUS  
6) Energy  –  Short Answer    Scientists at Brookhaven National Lab are studying Cooper pairs in iron-selenide superconductors. Cooper pairs are pairs of what subatomic particles?   ANSWER: ELECTRONS 2019 Regional Science Bowl – Round 16A  Page 4 TOSS-UP  7) Math  –  Short Answer    In a quadruple-elimination tournament, each game is played by two teams, there are no ties, and teams are eliminated when they have lost 4 times. What is the maximum number of games played if 41 teams enter?  
ANSWER: 163   BONUS  7) Math  –  Short Answer    When applying the Euclidean algorithm to find the greatest common divisor of 44 and 161, what is the remainder after the third step?  ANSWER: 14  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  8) Physics  –  Multiple Choice    Which of the following is necessarily true regarding capacitors?   W) For capacitance in parallel, the equivalent capacitance is less than that of any individual capacitor X) For capacitance in parallel, the equivalent capacitance is the sum of reciprocals of the individual capacitors Y) For capacitance in series, the equivalent capacitance is less than that of any individual capacitor Z) For capacitance in series, the equivalent capacitance is the sum of the individual capacitors   
ANSWER: Y) FOR CAPACITANCE IN SERIES, THE EQUIVALENT CAPACITANCE IS LESS THAN THAT OF ANY INDIVIDUAL CAPACITOR   BONUS  8) Physics  –  Short Answer    Consider an object placed one centimeter to the left of a diverging thin lens of focal length 5 centimeters. The virtual image that is formed will appear how many centimeters left of the lens?  
 ANSWER: 5/6 2019 Regional Science Bowl – Round 16A  Page 5 TOSS-UP  9) Earth and Space  –  Multiple Choice    Which of the following best describes why ocean water at 30 degrees latitude has higher salt content than water at the equator?  W) Most rivers flow into the ocean at the equator  X) Ice formation at high latitudes increases salinity  Y) Precipitation exceeds evaporation at the equator  Z) Low-salinity water upwells at the equator  
ANSWER: Y) PRECIPITATION EXCEEDS EVAPORATION AT THE EQUATOR   BONUS  9) Earth and Space  –  Short Answer     Identify all of the following three characteristics that describe a typical neritic zone in the ocean water column: 1) Oxygen-poor; 2) Photic;  3) Near-shore.  ANSWER: 2, 3  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  
10) Chemistry  –  Multiple Choice    When an alkene [al-KEEN] acts as a nucleophile, what specific part of the alkene is nucleophilic?   
W) The higher-energy carbon atom X) The lower-energy carbon atom Y) The carbon-carbon sigma bond Z) The carbon-carbon pi [pie]  bond   
ANSWER: Z) THE CARBON-CARBON PI [pie] BOND   BONUS  
10) Chemistry  –  Short Answer    N2O is in equilibrium with N2O4 in a transparent cylinder fitted with a piston. Identify all of the following three changes that would increase the number of 
N2O molecules in the cylinder: 1) Depressing the piston; 2) Increasing the temperature; 3) Adding nitrogen gas.    ANSWER: 2 2019 Regional Science Bowl – Round 16A  Page 6 TOSS-UP  11) Energy  –  Multiple Choice    Lawrence Berkeley National Lab scientists are studying the inflammasome, which is a structure that forms around flagellin. This protein is involved in the immune response to which of the following?   W) Paramecia X) Bacteria Y) Protists Z) Fungi   
ANSWER: X) BACTERIA   BONUS  11) Energy  –  Short Answer    Researchers at Argonne National Lab are researching spin coating as a technique to form thin films. Spin coating can be used to prepare photoresistors less than a micrometer thick, which can then be used in what technique?   ANSWER: LITHOGRAPHY (ACCEPT: PHOTOLITHOGRAPHY)  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  12) Biology  –  Short Answer    Adrenocorticotropic [ah-DREE-noh-kordih-koh-TROH-pik] hormone, vasopressin [VAY-zoh-pressin], and thyroid-stimulating hormone are all produced in what gland?  ANSWER: PITUITARY   BONUS  12) Biology  –  Short Answer    Identify all of the following three groups of animals that are monophyletic [mono-fye-LET-ik]: 1) Mammals; 2) Reptiles; 3) Birds.  ANSWER: 1, 3 2019 Regional Science Bowl – Round 16A  Page 7 TOSS-UP  13) Earth and Space  –  Multiple Choice    In meteorology, the atmosphere’s lapse rate has which of the following units?  W) Degrees Celsius per kilometer X) Watts per meter squared Y) Pascals per second  Z) Meters per second  ANSWER: W) DEGREES CELSIUS PER KILOMETER   BONUS  13) Earth and Space  –  Short Answer     Identify all of the following three mass wasting events in which the moving debris is typically coherent: 1) Solifluction; 2) Lahar [lah-HAHR];  3) Slump.  ANSWER: 1, 3  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  14) Math  –  Short Answer    The altitude to the hypotenuse of a right triangle divides the hypotenuse into segments of length 5 and 4. What is the length of the altitude?  ANSWER: 2√5   BONUS  14) Math  –  Short Answer    What is the standard deviation of the following list of 4 numbers:  5, 5, 9, 17?  ANSWER: 2√6 2019 Regional Science Bowl – Round 16A  Page 8 TOSS-UP  15) Physics  –  Multiple Choice    The Chernobyl disaster occurred, in part, due to the buildup of xenon-135[ZEE-non one thirty five] in the core. Which of the following best describes the role xenon-135 played in the core?   W) Neutron emitter X) Control rod Y) Neutron poison Z) Catalyst   ANSWER: Y) NEUTRON POISON   BONUS  15) Physics  –  Short Answer    Identify all of the following three processes that would increase the entropy of an ideal gas: 1) Reversible isothermal expansion; 2) Reversible  adiabatic [ad-ee-ah-BAT-ik] expansion; 3) Free expansion against zero pressure.  ANSWER: 1, 3  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  16) Energy  –  Short Answer    Scientists at Idaho National Lab have developed a new method to refine biodiesel. This novel process uses a carbon dioxide solvent in which the CO2 is in what specific phase?  ANSWER: SUPERCRITICAL FLUID (ACCEPT: SUPERCRITICAL)   BONUS  
16) Energy  –  Short Answer     Scientists at Brookhaven National Lab are part of the ATLAS experiment at CERN, which recently observed light-by-light scattering, where light at high energies can be scattered by what particle?   
ANSWER: PHOTON 2019 Regional Science Bowl – Round 16A  Page 9 TOSS-UP  17) Biology  –  Multiple Choice    In embryonic development, the archenteron is a precursor to what?   W) Gut X) Brain Y) Skeletal musculature Z) Skin   ANSWER: W) GUT     BONUS   17) Biology  –  Short Answer    Fluoxetine [floo-OX-eh-teen] and citalopram [sigh-TAL-eh-pram] are useful in treating anxiety because they inhibit the reuptake of what satiety-related neurotransmitter?   ANSWER: SEROTONIN (ACCEPT: 5-HT)   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP   18) Chemistry  –  Multiple Choice    Which of the following electron configurations is correct for the aqueous iron 2+ ion?   W) [Ar] 4s2 3d4 X) [Ar] 4s1 3d5 Y) [Ar] 3d6 Z) [Ar] 3d5 4p1   ANSWER: Y) [Ar] 3d6     BONUS   18) Chemistry  –  Multiple Choice    A heterogeneous [het-ur-oh-GENE-ee-us] catalyst surface catalyzes the hydrogenation reaction of ethylene to form ethane. Which of the following 
elementary steps would not occur?  
W) Hydrogen dissociating on the surface X) Gas phase addition of hydrogen to ethylene Y) Ethylene adsorbing Z) Adsorbed hydrogen adding to adsorbed ethylene  
ANSWER: X) GAS PHASE ADDITION OF HYDROGEN TO ETHYLENE 2019 Regional Science Bowl – Round 16A  Page 10 TOSS-UP  19) Math  –  Short Answer    In base 7, what is 4 times 6?  ANSWER: THREE-THREE (ACCEPT: 33)   BONUS  19) Math  –  Short Answer    What is the cross product of vectors 3i + 2j + k cross j?  ANSWER: –i + 3k (ACCEPT: –i + 0j + 3k, –1i + 3k, –1i + 0j + 3k  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  20) Biology  –  Short Answer    Identify all of the following three structures that are homologous [ha-MAWL-uh-gus] to a human hand: 1) Whale flipper; 2) Bat wing; 3) Bird claw.   ANSWER: 1, 2   BONUS  
20) Biology  –  Short Answer    Identify all of the following three groups of organisms that are protostomes: 1) Snails; 2) Sea cucumbers; 3) Earthworms.    
ANSWER: 1, 3 2019 Regional Science Bowl – Round 16A  Page 11 TOSS-UP  21) Physics  –  Short Answer    Kaons [KAY-ons] and pions [PIE-ons] are classified as what type of composite particle that consists of a quark and an anti-quark?   ANSWER: MESONS   BONUS  21) Physics  –  Short Answer    What is the moment of inertia, in kilogram meters squared, of a 5-kilogram uniform solid sphere of radius 3 meters rotating about an axis that is tangent to its surface?  ANSWER: 63  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TOSS-UP  22) Earth and Space  –  Short Answer    What two planets in our solar system have the most eccentric orbits?   ANSWER: MARS AND MERCURY (ACCEPT IN EITHER ORDER)   BONUS  22) Earth and Space  –  Short Answer    An astronaut is 4 light-years from Alpha Centauri, and traveling toward it. If the astronaut is traveling at 0.6c, then, from the reference frame of the astronaut, how far, in light years, will the journey appear to be?   ANSWER: 3.2 (ACCEPT: 3 1/5, 16/5) 2019 Regional Science Bowl – Round 16A  Page 12 TOSS-UP  23) Chemistry  –  Short Answer    What are the two possible molecular geometries for a five-coordinate transition metal compound?  ANSWER: TRIGONAL BIPYRAMIDAL AND SQUARE BIPYRAMIDAL   BONUS  23) Chemistry  –  Short Answer    Permanganate [pur-MAYNG-en-ate] ion is used to oxidize iron(II) to iron(III) in neutral aqueous solution. What insoluble precipitate is the byproduct of this reaction?  ANSWER: MANGANESE DIOXIDE (ACCEPT: MANGANESE(IV) OXIDE, MnO2)`

	if err != nil {
		t.Errorf("failed to convert to string with error %q", err)
	}

	if got != want {
		t.Errorf("wanted %q, got %q", want, got)
	}
}
